### PR TITLE
Feat: A realtime feature in Cases model.

### PR DESCRIPTION
**Pull request by jhon-andrew**
Re: #9 
* Included socket.io
* Created test-realtime.html for testing.

### CODE REVIEW

**Comment by JHNLWHD** [comment]
@jhon-andrew  please amend your commit message according to the following tag/prefixes.

image

**Comment by jhon-andrew** [comment]
> @jhon-andrew please amend your commit message according to the following tag/prefixes.
> 
> image

Okay, I'm using a different environment so I didn't notice that.

**Comment by jhon-andrew** [comment]
To use the feature, frontend will need to include Socket.IO Client:

Include via script tag:
```html
<script src="./socket.io/socket.io.js"></script>
```

Or npm install `socket.io-client` and import it in code.
```js
const io = require('socket.io-client')
// OR
import io from 'socket.io-client'
```

---

To listen for new added cases:
```js
socket.on('case.new', data => {
  // The `data` is an object containing the new case entry.
  alert('A new case has been recorded.\nSee console logs.')
  console.log(Date.now(), 'NEW CASE:', { data })
})
```

To listen for case updates:
```js
socket.on('case.updated', data => {
  // The `data` is an object containing the updated case.
  alert('A case has been updated.\nSee console logs.')
  console.log(Date.now(), 'UPDATED CASE:', { data })
})
```

**Comment by jbienesdev** [comment]
This is noted @jhon-andrew 🤘

**Comment by JHNLWHD** [comment]
@jhon-andrew  One more thing about this PR, please update the description. Kindly reference the issue number related to this PR. Thanks 👍 

Sample:
image

**Comment by JHNLWHD** [comment]
> > @jhon-andrew please amend your commit message according to the following tag/prefixes.
> > image
> 
> Okay, I'm using a different environment so I didn't notice that.

image

Please also update/amend the commit message itself. Thanks 👍

**Comment by JHNLWHD** [comment]
LGTM too in code-level 🚀 👨‍💻 Just requesting change/update in commit message to align things here.

**Pull request merged**
